version: "3"
services:

  web:
    image: "hub.egistic.kz/nginx:latest"
    restart: "always"
    expose:
      - "80"
    environment:
      - "DOMAIN_NAME=${DOMAIN_NAME}"
      - "PROXY_PASS=http://app:80"
    volumes:
      - "./config/:/etc/nginx/conf.d/"
      - tumar-static:/static
      - media:/media
    networks:
      - "arys"
    labels:
      - "traefik.frontend.rule=Host:${DOMAIN_NAME}"
    command: /bin/bash -c "nginx -g 'daemon off;'"

  app:
    image: "hub.egistic.kz/tumar:latest"
    restart: "always"
    expose:
      - "3000"
    networks:
      - "arys"
      - "postgis"
      - "rabbit"
      - "geoserver"
    volumes:
      - "/nfs/storage/imgback_rasters:/imgback_rasters"
      - ".:/code"
      - tumar-static:/code/static
      - media:/code/media
    environment:
      - "DEFAULT_DB_HOST=db_default"
      - "DEFAULT_DB_PORT=5432"
      - "DEFAULT_DB_NAME=tumar"
      - "DEFAULT_DB_USER=docker"
      - "DEFAULT_DB_PASSWORD=docker"
    command: >
      bash -c "./manage.py collectstatic --noinput &&
              ./manage.py migrate &&
              ./manage.py compilemessages &&
              uwsgi --ini config/uwsgi.ini"

  celerybeat_worker:
    image: "hub.egistic.kz/tumar:latest"
    restart: "always"
    #user: "1000:1000"
    expose:
      - "80"
    networks:
      - "arys"
      - "postgis"
      - "rabbit"
      - "geoserver"
    volumes:
      - "/nfs/storage/imgback_rasters:/imgback_rasters"
      - ".:/code"
    environment:
      - "DEFAULT_DB_HOST=db_default"
      - "DEFAULT_DB_PORT=5432"
      - "DEFAULT_DB_NAME=tumar"
      - "DEFAULT_DB_USER=docker"
      - "DEFAULT_DB_PASSWORD=docker"
    command: >
      bash -c "celery -A tumar worker -Q tumar_celerybeat, tumar_handler_process_cadastres -c 3 -n tumar_worker -l INFO"

  celerybeat:
    image: "hub.egistic.kz/tumar:latest"
    restart: "always"
    #user: "1000:1000"
    expose:
      - "80"
    networks:
      - "arys"
      - "postgis"
      - "rabbit"
      - "geoserver"
    volumes:
      - "/nfs/storage/imgback_rasters:/imgback_rasters"
      - ".:/code"
    environment:
      - "DEFAULT_DB_HOST=db_default"
      - "DEFAULT_DB_PORT=5432"
      - "DEFAULT_DB_NAME=tumar"
      - "DEFAULT_DB_USER=docker"
      - "DEFAULT_DB_PASSWORD=docker"
    command: >
      bash -c "celery beat -A tumar -l INFO --pidfile /tmp/celerybeat.pid -s /tmp/celerybeat-schedule"

networks:
  arys:
    external: true
  postgis:
    external: true
  rabbit:
    external:
      name: "rabbit"
  geoserver:
    external:
      name: "geoserver"

volumes:
  media:
  tumar-static: