version: "3"
services:

  web:
    image: "tumar/nginx:latest"
    restart: "always"
    ports:
      - "80:80"
    volumes:
      - "./config/:/etc/nginx/conf.d/"
      - ./static:/static
      - ./media:/media
    depends_on:
      - app
    networks:
      - "tumar"
    command: /bin/bash -c "nginx -g 'daemon off;'"

  app:
    image: "tumar/app:latest"
    restart: "always"
    user: ${CURRENT_UID}
    expose:
      - "3000"
    networks:
      - "tumar"
      - "main_db"
    volumes:
      - ".:/code"
      - ./static:/code/static
      - ./media:/code/media
    command: ["./config/wait_for_postgres.sh"] 

  memcached:
    image: memcached:1.6.5
    expose:
      - "11211"
    networks:
      - "tumar"

  worker:
    image: "tumar/app:latest"
    restart: "always"
    user: ${CURRENT_UID}
    networks:
      - "tumar"
      - "main_db"
    volumes:
      - ".:/code"
    command: >
      bash -c "celery -A tumar worker -Q tumar_celerybeat,tumar_handler_process_cadastres,community_push_notifications -c 4 -n tumar_worker -l INFO --uid $(id -u)"
  
  celerybeat:
    image: "tumar/app:latest"
    restart: "always"
    user: ${CURRENT_UID}
    networks:
      - "tumar"
      - "main_db"
    volumes:
      - ".:/code"
    command: >
      bash -c "celery beat -A tumar -l INFO --pidfile /tmp/celerybeat.pid -s /tmp/celerybeat-schedule"

networks:
  tumar:
    external: true
  main_db:
    external: true
