version: "3"
services:

  web:
    image: "hub.egistic.kz/nginx:latest"
    restart: "always"
    expose:
      - "80"
    environment:
      - "DOMAIN_NAME=${DOMAIN_NAME}"
      - "PROXY_PASS=http://app:80"
    volumes:
      - "../nginx/conf.d:/etc/nginx/conf.d/templates"
      - /static:/static
    networks:
      - "arys"
    labels:
      - "traefik.frontend.rule=Host:${DOMAIN_NAME}"
    command: /bin/bash -c "envsubst '$${DOMAIN_NAME} $${PROXY_PASS}' < /etc/nginx/conf.d/templates/arys.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

  app:
    image: "hub.egistic.kz/tumar:latest"
    restart: "always"
    expose:
      - "80"
    networks:
      - "arys"
      - "postgis"
    volumes:
      - ".:/code"
      - /static:/static
    command: >
      bash -c "./manage.py migrate &&
               ./manage.py compilemessages &&
               ./manage.py runserver 0.0.0.0:80"
    environment:
      - "DEFAULT_DB_HOST=db_default"
      - "DEFAULT_DB_PORT=5432"
      - "DEFAULT_DB_NAME=tumar"
      - "DEFAULT_DB_USER=docker"
      - "DEFAULT_DB_PASSWORD=docker"
      - "DJANGO_SECRET_KEY=production"
      - "DJANGO_CONFIGURATION=Production"
      - "DJANGO_SETTINGS_MODULE=tumar.config.production"

networks:
  arys:
    external: true
  postgis:
    external: true